### ISSUE TITLE
sensor broken after 0.84 release

### ISSUE THREAD

**Issue by juan11perez** [abmantis/homeassistant-custom-components#3]
Thank you for this component.
It appears to be broken after 0.84 release
getting these errors:
```
018-12-16 17:05:48 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.binary_sensor.device_tracker_sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/loader.py", line 92, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/binary_sensor/device_tracker_sensor.py", line 28, in <module>
    from homeassistant.helpers.restore_state import async_get_last_state
ImportError: cannot import name 'async_get_last_state'
```

**Comment by abmantis** [comment]
Fixed by #4

**Comment by dgomes** [comment]
I actually fixed a different sensor 🗡  😉

**Comment by abmantis** [comment]
@dgomes thanks for noticing that! Clearly, I should not be closing issues after midnight on a Sunday 🙄

**Comment by Ernst79** [comment]
According to the homeassistant forum, this can be fixed by removing (or comment out) the following line:

from homeassistant.helpers.restore_state import async_get_last_state
